### ISSUE TITLE
Where is the Code

### ISSUE THREAD

**Issue by wjl2244** [SysCV/TrafficBots#2]
Hello author, I am very interested in your work, but I found that I can't find the open source code here, so I would like to ask when you will add?

**Comment by zhejz** [comment]
I'm working on the Waymo Open Sim Agent Challenge and I've underestimated the workload.
Besides, I'm very busy recently because of various reasons.
I apologize for the delay. The code will be there within a month.

**Comment by ntutangyun** [comment]
Hi just like to follow up with the open source request...

**Comment by zhejz** [comment]
Sorry for the delay. The code is now available at https://github.com/zhejz/TrafficBots
